# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming_event.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'streaming_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15streaming_event.proto\x12\x0epubsub_demo.v1\"\xe5\x02\n\x0eStreamingEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x14\n\x0cpayload_type\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x44\n\x0cpod_env_vars\x18\x06 \x03(\x0b\x32..pubsub_demo.v1.StreamingEvent.PodEnvVarsEntry\x12\x14\n\x0cis_corrupted\x18\x07 \x01(\x08\x12\x1a\n\x12schema_fingerprint\x18\x08 \x01(\t\x12\x13\n\x0bpayload_uri\x18\t \x01(\t\x12\x1a\n\x12uncompressed_bytes\x18\n \x01(\x03\x12\x18\n\x10\x63ompressed_bytes\x18\x0b \x01(\x03\x1a\x31\n\x0fPodEnvVarsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMINGEVENT_PODENVVARSENTRY']._loaded_options = None
  _globals['_STREAMINGEVENT_PODENVVARSENTRY']._serialized_options = b'8\001'
  _globals['_STREAMINGEVENT']._serialized_start=42
  _globals['_STREAMINGEVENT']._serialized_end=399
  _globals['_STREAMINGEVENT_PODENVVARSENTRY']._serialized_start=350
  _globals['_STREAMINGEVENT_PODENVVARSENTRY']._serialized_end=399
# @@protoc_insertion_point(module_scope)
